# Generated by Django 5.0.6 on 2024-05-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
    ]
